-- Create ROLE_TYPE table
CREATE TABLE ROLE_TYPE (
    ROLE_ID SERIAL PRIMARY KEY,
    ROLE_NAME VARCHAR(100) NOT NULL
);

-- Create ACCOUNT table
CREATE TABLE ACCOUNT (
    ACC_ID SERIAL PRIMARY KEY,
    ACC_USERNAME VARCHAR(100) NOT NULL UNIQUE,
    ACC_PASSWORD VARCHAR(100) NOT NULL,
    ROLE_ID INT REFERENCES ROLE_TYPE(ROLE_ID)
);

-- Create USER_PROFILE table with email address
CREATE TABLE USER_PROFILE (
    USER_ID SERIAL PRIMARY KEY,
    USER_FNAME VARCHAR(100) NOT NULL,
    USER_LNAME VARCHAR(100) NOT NULL,
    USER_CONTACTNUM CHAR(11) UNIQUE,
    USER_EMAIL VARCHAR(100) UNIQUE NOT NULL, 
    ACC_ID INT REFERENCES ACCOUNT(ACC_ID)
);


-- Create NOTIFICATION table
CREATE TABLE NOTIFICATION (
    NOTIF_ID SERIAL PRIMARY KEY,
    NOTIF_MESSAGE TEXT NOT NULL,
    NOTIF_DATE_SENT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACC_ID INT REFERENCES ACCOUNT(ACC_ID)
);

-- Create SUPPLIER table
CREATE TABLE SUPPLIER (
    SUPPLIER_ID SERIAL PRIMARY KEY,
    SUPPLIER_FNAME VARCHAR(100) NOT NULL,
    SUPPLIER_LNAME VARCHAR(100) NOT NULL,
    SUPPLIER_ADDRESS TEXT NOT NULL,
    SUPPLIER_CONTACT VARCHAR(15) NOT NULL
);

-- Create PURCHASE_ORDER table
CREATE TABLE PURCHASE_ORDER (
    PO_ID SERIAL PRIMARY KEY,
    PO_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PO_SHIP_ADDRESS TEXT NOT NULL,
    PO_DELIVERY_TERM VARCHAR(100),
    PO_PAY_TERM VARCHAR(100),
    PO_STATUS VARCHAR(100),
    PO_TERM_CONDITION TEXT,
    PO_DATE_APPROVAL TIMESTAMP,
	QUANTITY INT NOT NULL	DEFAULT 1,
    SUPPLIER_ID INT REFERENCES SUPPLIER(SUPPLIER_ID),
    ACC_ID INT REFERENCES ACCOUNT(ACC_ID),
	ITEM_ID INT REFERENCES ITEM(ITEM_ID)
);

-- Create RECEIVING_MEMO table
CREATE TABLE RECEIVING_MEMO (
    MEMO_ID SERIAL PRIMARY KEY,
    MEMO_DATE_ISSUED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MEMO_SIGNATURE VARCHAR(255),
    MEMO_VERDATE TIMESTAMP,
    MEMO_CONDITION TEXT,
    MEMO_QTY_RECEIVED INT,
    SUPPLIER_ID INT REFERENCES SUPPLIER(SUPPLIER_ID),
    PO_ID INT REFERENCES PURCHASE_ORDER(PO_ID),
    ACC_ID INT REFERENCES ACCOUNT(ACC_ID)
);

-- Create REQUISITION table
CREATE TABLE REQUISITION (
    REQ_ID SERIAL PRIMARY KEY,
    REQ_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REQ_STATUS VARCHAR(100),
    REQ_DATE_APPROVAL TIMESTAMP,
    ACC_ID INT REFERENCES ACCOUNT(ACC_ID),
    REQ_ITEM_ID INT REFERENCES REQUESTED_ITEM(REQ_ITEM_ID)
);

-- Create REQUESTED_ITEM table
CREATE TABLE REQUESTED_ITEM (
    REQ_ITEM_ID SERIAL PRIMARY KEY,
    REQ_ITEM_NAME VARCHAR(255),
    REQ_ITEM_DESC TEXT,
    REQ_ITEM_CATEGORY VARCHAR(100),
    REQ_ITEM_QTY INT,
    REQ_ITEM_UNIT VARCHAR(50),
    ITEM_ID INT REFERENCES ITEM(ITEM_ID)
);

-- Create ITEM table
CREATE TABLE ITEM (
    ITEM_ID SERIAL PRIMARY KEY,
    ITEM_NAME VARCHAR(255),
    ITEM_DESC TEXT,
    ITEM_UNIT VARCHAR(50),
    ITEM_QTY INT,
    ITEM_UNIT_PRICE DECIMAL(10, 2),
    ITEM_STATUS VARCHAR(50),
    CATEGORY_ID INT REFERENCES ITEM_CATEGORY(CATEGORY_ID)
);

-- Create ITEM_CATEGORY table
CREATE TABLE ITEM_CATEGORY (
    CATEGORY_ID SERIAL PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100)
);

-- Create DELIVERY table
CREATE TABLE DELIVERY (
    DELIVER_ID SERIAL PRIMARY KEY,
    DELIVER_STATUS VARCHAR(100),
    DELIVER_REMARKS TEXT,
    DELIVER_QTY INT,
    ACC_ID INT REFERENCES ACCOUNT(ACC_ID),
    PO_ID INT REFERENCES PURCHASE_ORDER(PO_ID),
    SUPPLIER_ID INT REFERENCES SUPPLIER(SUPPLIER_ID)
);

-- Create PO_LINE_ITEM table
CREATE TABLE PO_LINE_ITEM (
    LINE_ID SERIAL PRIMARY KEY,
    LINE_QTY INT,
    LINE_UNIT_PRICE DECIMAL(10, 2),
    LINE_TOTAL_COST DECIMAL(10, 2),
    PO_ID INT REFERENCES PURCHASE_ORDER(PO_ID),
    ITEM_ID INT REFERENCES ITEM(ITEM_ID)
);

-- Create ISSUE_LOG table
CREATE TABLE ISSUE_LOG (
    ISSUE_ID SERIAL PRIMARY KEY,
    ISSUE_TYPE VARCHAR(100),
    ISSUE_DESC TEXT,
    ISSUE_EVIDENCE TEXT,
    ISSUE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ISSUE_COMMENT TEXT,
    DELIVER_ID INT REFERENCES DELIVERY(DELIVER_ID),
    LINE_ID INT REFERENCES PO_LINE_ITEM(LINE_ID)
);


